# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba7c4e038a1c6e7c0a324901e140ef46"
name = "masterclass-declarative-data"
handle = "masterclass-declarative-data"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,write_customers,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[metaobjects.app.shipping_messages.access]
admin = "merchant_read_write"
storefront = "public_read"

[metaobjects.app.shipping_messages.fields.state_province]
name = "Province Code"
type = "single_line_text_field"
required = true

  [metaobjects.app.shipping_messages.fields.state_province.validations]
  choices = [
    "ON","BC","AB","QC","NS","NB","MB","SK","PE","NL","YT","NT","NU","AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"
  ]

[metaobjects.app.shipping_messages.fields.message2]
type = "single_line_text_field"
required = true
name = "Message"

[metaobjects.app.shipping_messages.fields.start_time]
type = "date_time"
name = "Start Time"

[metaobjects.app.shipping_messages.fields.end_time]
type = "date_time"
name = "End Time"

[product.metafields.app.max_purchase_quantity]
name = "Max Purchase Quantity"
type = "number_integer"
validations.min = 0
access.admin = "merchant_read_write"

[product.metafields.app.max_quantity_message]
name = "Max Quantity Message"
type = "single_line_text_field"
access.admin = "merchant_read_write"

[customer.metafields.app.allow_purchase_over_max]
name = "Allow Purchase Over Max"
type = "boolean"
access.admin = "merchant_read_write"
access.customer_account = "read"

