api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "max-quantity"
type = "function"
uid = "7b01d540-cf78-46a2-87b4-b5edd255d593"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.validation.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

